services:
  frontend:
    image: ghcr.io/profiidev/images/node-gnu-dev:main@sha256:045e802386b675aa5a3e46cc04c23e85f957e2ce82a0afd4b52034e380987055
    restart: unless-stopped
    user: '${HOST_UID:-0}:${HOST_GID:-0}'
    volumes:
      - ./frontend:/app/frontend
      - ./node_modules:/app/node_modules
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
    tty: true
    ports:
      - '5174:5174'
    networks:
      - nginx
    working_dir: /app/frontend
    command: npm run dev -- --host
    #command: npm i

  backend:
    image: ghcr.io/profiidev/images/rust-musl-watch:main@sha256:a82703d3509314ca08c665c921114c9b0cbee2c464b2a038e39c47e9eef05f9a
    user: '${HOST_UID:-0}:${HOST_GID:-0}'
    volumes:
      - ./backend:/app
    networks:
      - nginx
    tty: true
    ports:
      - '5173:8000'
    entrypoint: ['tini', '--']
    command: ['cargo', 'watch', '-x', 'run']
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    networks:
      - nginx
    ports:
      - '9301:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'test']
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 1s

networks:
  nginx:
