// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:5173" | (string & {});
};

export type TestDummyData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/dummy/test";
};

export type TestDummyErrors = {
  /**
   * An error occurred
   */
  "4XX": unknown;
  /**
   * An error occurred
   */
  "5XX": unknown;
};

export type TestDummyResponses = {
  /**
   * plain text
   */
  200: unknown;
};
