// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:5173' | (string & {});
};

export type TestData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/dummy/test';
};

export type TestErrors = {
  /**
   * An error occurred
   */
  '4XX': unknown;
  /**
   * An error occurred
   */
  '5XX': unknown;
};

export type TestResponses = {
  /**
   * plain text
   */
  200: unknown;
};
