name: Checks and Validation
on:
  pull_request:

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
        with:
          components: clippy,rustfmt

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          cache-on-failure: true
          shared-key: "linter_cache"
      - uses: bahmutov/npm-install@v1

      - name: Generate svelte data
        run: |
          echo "BACKEND_URL=http://localhost:8000" > frontend/.env
          cd frontend && npm run sync

      - name: Run linters
        uses: profiidev/rust-lint-action@e9435ea64793ce035116e328195eb0c786a46f5a # v4
        with:
          rustfmt: true
          clippy: true
          auto_fix: true
          svelte: true
          svelte_args: "--ignore target"
          tsc: true
          tsc_dir: frontend
          oxlint: true
          oxfmt: true
          git_sign_commits: true
          github_token: ${{ steps.app-token.outputs.token }}
