name: Create Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release-tag:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release-version') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - name: Checkout code
        with:
          token: ${{ steps.app-token.outputs.token }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Create tag
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          VERSION=$HEAD_REF
          VERSION=${VERSION#chore/release-version-}
          echo "Creating tag for version $VERSION"
          git tag "$VERSION"
          git push origin "$VERSION"

  create-release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - name: Create Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3
        with:
          tag_name: ${{ github.ref_name }}
          token: ${{ steps.app-token.outputs.token }}
          name: Release ${{ github.ref_name }}
          body: |
            Release version ${{ github.ref_name }} has been created.
          generate_release_notes: true
